[context.production.branch-deploy]
    command = "mv robots-preview.txt public/robots.txt"

[context.production]
    command = "mv robots-production.txt public/robots.txt"
[[context.production.plugins]]
package = "@netlify/plugin-sitemap"
